### ISSUE TITLE
Data Request: Complete Mutation Information  of BBC Patients

### ISSUE THREAD

**Issue by violetliaoxy** [rt2lab/bc_bilat_neo#1]
## Data Request: Complete Mutation Information  of BBC Patients

**Request Background:**
I recently came across your research study titled "Evolution of synchronous female bilateral breast cancers and response to treatment", and it has been incredibly valuable for my current project. 
I am interested in using the breast cancer mutation data you provided to calculate mutational signatures in patients.

**Request Details:**
However, I couldn't find the complete mutation information, including REF and ALT, in the publicly available data.
I kindly request if you could provide the necessary information, such as the REF and ALT details for the mutations in the dataset. Having this information is crucial for accurately calculating mutational signatures in patients and would greatly contribute to the success of my project.

Thank you for your attention to this matter, and I genuinely appreciate your efforts in making the data available. If there are any constraints or limitations regarding the release of this information, please let me know, and I am open to discussing potential alternatives or solutions.

**Comment by judithabk6** [comment]
Dear violetliaoxy

Thank you for your interest for our study.
Indeed, those columns should have been included in the shared mutation data.
Here is the version with those two columns.

Let us know if you need anything else
Best wishes
[bilat_mutations_ref_alt.csv](https://github.com/rt2lab/bc_bilat_neo/files/13404832/bilat_mutations_ref_alt.csv)

**Comment by violetliaoxy** [comment]
Dear judithabk6,

Thank you for providing the requested data, including the REF and ALT details. Your prompt response and assistance are greatly appreciated. Having this complete mutation information is crucial for my project's success in accurately calculating mutational signatures in patients.

If there are any further updates or constraints regarding the data, please let me know. I am open to discussing alternatives or solutions.

Thank you again for your support.

Best regards

**Comment by judithabk6** [comment]
Dear violetliaoxy,

I am not sure I understand what you need. What extra information or format is missing from the current mutation table? We have computed the signature analysis (for single nucleotide variants) only with the provided information (sample, position in the genome and ref, alt columns that were indeed missing from the first table). You can get the flanking nucleotides in the genome using the code in 14_3_get_trinucleotide_context.R.

Let me know how I can help

Best wishes

**Comment by violetliaoxy** [comment]
Dear judithabk6,

I apologize for not replying in a timely manner. The reason I requested data from you is primarily because I couldn't find the REF and ALT columns in the mutation information provided in the supplementary materials of your published article. However, I need these two columns of information to calculate the mutational signatures. The data you have provided has greatly facilitated my project.

Additionally, the code you mentioned could also be very helpful for my project. I hope we can stay in touch, and I am willing to discuss further if necessary. Thank you very much for your assistance.

Best regards
